// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"giphy_microservices/app"
)

// Injectors from wire.go:

func InitializeApp() *app.App {
	appApp := app.InitApp()
	return appApp
}
